# Generated by Django 3.1.5 on 2021-01-21 23:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='athlete',
            name='events',
            field=models.ManyToManyField(db_column='athEvents', related_name='atheletes', to='challenge.Event'),
        ),
        migrations.AlterField(
            model_name='athleteinfo',
            name='athlete',
            field=models.ForeignKey(db_column='atiAthId', default=0, on_delete=django.db.models.deletion.CASCADE, related_name='athlete_infos', to='challenge.athlete'),
        ),
        migrations.AlterField(
            model_name='eventinfo',
            name='event',
            field=models.ForeignKey(db_column='eviEveId', default=0, on_delete=django.db.models.deletion.CASCADE, related_name='event_infos', to='challenge.event'),
        ),
    ]
