# Generated by Django 3.1.5 on 2021-01-23 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0002_auto_20210121_2314'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='athlete',
            name='events',
        ),
        migrations.AddField(
            model_name='athleteinfo',
            name='event',
            field=models.ManyToManyField(blank=True, db_column='atiEveId', default=0, related_name='athlete_infos', to='challenge.Event'),
        ),
        migrations.AddField(
            model_name='event',
            name='city',
            field=models.CharField(db_column='eveCity', default='', max_length=45),
        ),
        migrations.AddField(
            model_name='event',
            name='season',
            field=models.CharField(db_column='eveSeason', default='', max_length=10),
        ),
        migrations.AddField(
            model_name='event',
            name='sport',
            field=models.CharField(db_column='eveSport', default='', max_length=45),
        ),
        migrations.AddField(
            model_name='event',
            name='year',
            field=models.CharField(db_column='eveYear', default='', max_length=45),
        ),
        migrations.DeleteModel(
            name='EventInfo',
        ),
    ]
