# Generated by Django 3.1.5 on 2021-01-21 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0002_auto_20210121_2314'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='athlete_infos',
            field=models.ManyToManyField(db_column='eveAtiId', related_name='events', to='challenge.AthleteInfo'),
        ),
    ]
