# Generated by Django 3.1.5 on 2021-01-22 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0002_auto_20210121_2314'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='athlete',
            name='events',
        ),
        migrations.AddField(
            model_name='athleteinfo',
            name='events',
            field=models.ManyToManyField(db_column='atiEvents', related_name='ath_infos', to='challenge.Event'),
        ),
    ]
