# Generated by Django 3.1.5 on 2021-01-23 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0003_auto_20210122_0129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='athleteinfo',
            name='events',
            field=models.ManyToManyField(blank=True, db_column='atiEvents', related_name='ath_infos', to='challenge.Event'),
        ),
    ]
