# Generated by Django 3.1.5 on 2021-01-24 03:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0004_auto_20210123_1823'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='athleteinfo',
            unique_together={('athlete', 'team')},
        ),
    ]
