# Generated by Django 3.1.5 on 2021-01-24 23:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0005_auto_20210124_0345'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='athleteinfo',
            unique_together={('athlete', 'sex', 'team', 'age', 'height', 'weight', 'medal')},
        ),
        migrations.AlterUniqueTogether(
            name='event',
            unique_together={('event_name', 'city', 'sport', 'season', 'year', 'games')},
        ),
    ]
