# Generated by Django 3.1.5 on 2021-01-24 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0006_auto_20210124_2312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_name',
            field=models.CharField(db_column='eveName', max_length=132),
        ),
    ]
