# Generated by Django 3.1.5 on 2021-01-24 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0007_auto_20210124_2313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='athlete',
            name='athlete_name',
            field=models.CharField(db_column='athName', max_length=65, unique=True),
        ),
    ]
