# Generated by Django 3.1.5 on 2021-01-24 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0009_remove_athlete_athlete_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='athlete',
            name='athlete_name',
            field=models.CharField(db_column='athName', default='', max_length=255, unique=True),
        ),
    ]
